### PR TITLE
Fix duplicate import of headers from raw request

### LINKED ISSUE #27: 415 Unsupported Media Type
Given:

`type Api =
    ReqBody '[JSON] Int
    :> Get '[JSON] Int

api = Proxy :: Proxy Api

main = quickHttpServe (serveSnap api return)`

with:

`curl -i -X GET -H "Content-Type: application/json" -d '666' http://localhost:8000/`

i get back a "415 Unsupported Media Type", witch is weird to me. But if i try:

`curl -i -X GET -H "Content-Type: application/json;foo=bar" -d '666' http://localhost:8000/`

or even:

`curl -i -X GET -H "Content-Type: application/json;=" -d '666' http://localhost:8000/`

ir returns the expected 666. I don't understand why. Any clues?

### PR DESCRIPTION
**Pull request by imalsogreg**
Fixes #27 

`RoutingApplication.hs` was pulling request headers from the raw snap request and adding them to the `Request` used by servant for routing. These headers were already being imported by `snapToApplication`, so we were adding them twice. Duplicate `Content-Type: application/json` headers apparently can not be parsed unless they include the `;charset=utf-8` suffix.

### CODE REVIEW

File: src/Servant/Server/Internal/RoutingApplication.hs [hunk 1]
```diff
@@ -49,36 +52,8 @@ data RouteResult a =
...
-  --   , show snapResp
-  --   , "----------"
-  --   , "rspnd"
-  --   , show rspnd
-  --   ]
-
-  return rspnd
-
-  -- snapReq  <- getRequest
-  -- r        <- ra (request `addHeaders` headers snapReq) routingRespond
```
Comment (imalsogreg) [inline src/Servant/Server/Internal/RoutingApplication.hs:77]: This is the only important part of the PR - removing the addition of `snapReq`'s headers to `request`. These headers are _already_ added by `snapToApplication`.
